# Generated by Django 4.2.4 on 2023-08-22 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='image',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='deliverycrew',
            name='image',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='manager',
            name='image',
            field=models.CharField(max_length=200),
        ),
    ]
